version: "3.9"

services:
  bank-card-service:
    image: bank-card-service
    container_name: bank-card-service
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: postgres:15.2
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U username -d bank"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


